### ISSUE TITLE
IMPROVEMENT: Add the ability to change some registers

### ISSUE THREAD

**Issue by stripu** [sabatex/NetDaemonApps.InverterAnenji-4kw-7.2kw#2]
One thing if i may suggest:
Please implement changing some of the inverter settings via HA, for example:

Register: 301 "Output priority" {"0": "Utility-PV-Battery","1": "PV-Utility-Battery","2": "PV-Battery-Utility"}
Register: 331 "Battery charging priority" {"0": "Utility priority;","1": "PV priority;","2": "PV is at the same level as the Utility;","3": "Only PV charging is allowed;"}

Some of these settings could help in creating automations based on certain factors, so they could be very useful.

Thank you again for your work!

**Comment by sabatex** [comment]
Done.
I'm waiting for a description of the automation settings.

**Comment by stripu** [comment]
Awesome implementation! 
I've modified mine with a new mode in OutputPriority.cs:
SUF = 4 //On-Grid Mode

I have had this mode automatically added to my inverter after using it for a day or so, and it's very interesting: It's behaving as an off-grid inverter, and it's pushing current back in the grid (utility) as well, in case there is unused PV power.
It's pretty great in my use case as my inverter is in the garage, and before i changed it i used to have a completely off-grid inverter, which was not performing that great, and a lot of PV power was unused. Now with the SUF mode, I can have extra PV power pushed to the house, so it can lower my grid usage, and it works pretty good.
Also, because our power distributor has installed bidirectional meters, the meter is not registering any extra power as usage.
As an extra, in SUF mode, if there's no power coming in through the utility line, like if there's an outage, the inverter automatically behaves as a off-grid inverter, using the power from the battery to power my garage, and it doesn't send any power back to the input (utility), so there's no danger of getting electrocuted if there's no power from the utility.

I'll get back to you once i set up all the automations.
Thanks again!!

**Comment by nokia80** [comment]
> One thing if i may suggest: Please implement changing some of the inverter settings via HA, for example:
> 
> Register: 301 "Output priority" {"0": "Utility-PV-Battery","1": "PV-Utility-Battery","2": "PV-Battery-Utility"} Register: 331 "Battery charging priority" {"0": "Utility priority;","1": "PV priority;","2": "PV is at the same level as the Utility;","3": "Only PV charging is allowed;"}
> 
> Some of these settings could help in creating automations based on certain factors, so they could be very useful.
> 
> Thank you again for your work!

Hi @stripu,

Can we add more inverter functions?

**Comment by sabatex** [comment]
Adding additional features will negatively impact stability. Status registers are read in one packet. Registers that can be changed are read only individually. It is not advisable to read them without a special need. All other parameters can be set directly on the inverter. If you have ideas for automation using other registers in HomeAssistant, please write.

**Comment by nokia80** [comment]
> Adding additional features will negatively impact stability. Status registers are read in one packet. Registers that can be changed are read only individually. It is not advisable to read them without a special need. All other parameters can be set directly on the inverter. If you have ideas for automation using other registers in HomeAssistant, please write.

hi @sabatex,

I understand completely but I miss the data of the daily use I can't find this sensor also I can't find SOC, the following list is a basic list if all entries would work it would be great:

 i use the Sunsynk Power Flow Card configuration the sunsynk is deafult i have changes a lot to my inverter 

entities:
use_timer_248: switch.sunsynk_toggle_system_timer
priority_load_243: switch.sunsynk_toggle_priority_load
inverter_voltage_154: sensor.sunsynk_inverter_voltage
load_frequency_192: sensor.sunsynk_load_frequency
inverter_current_164: sensor.sunsynk_inverter_current
inverter_power_175: sensor.sunsynk_inverter_power
grid_connected_status_194: binary_sensor.sunsynk_grid_connected_status
inverter_status_59: sensor.sunsynk_overall_state 
day_battery_charge_70: sensor.sunsynk_day_battery_charge
 day_battery_discharge_71: sensor.sunsynk_day_battery_discharge
 battery_voltage_183: sensor.sunsynk_battery_voltage
 battery_soc_184: sensor.sunsynk_battery_soc
 battery_power_190: sensor.sunsynk_battery_power
 battery_current_191: sensor.sunsynk_battery_current
 grid_power_169: sensor.sunsynk_grid_power
 day_grid_import_76: sensor.sunsynk_day_grid_import
 day_grid_export_77: sensor.sunsynk_day_grid_export
 grid_ct_power_172: sensor.sunsynk_grid_ct_power
 day_load_energy_84: sensor.sunsynk_day_load_energy
 essential_power: none
 nonessential_power: none
 aux_power_166: sensor.sunsynk_aux_power
 day_pv_energy_108: sensor.sunsynk_day_pv_energy
 pv1_power_186: sensor.sunsynk_pv1_power
 pv2_power_187: sensor.sunsynk_pv2_power
 pv1_voltage_109: sensor.sunsynk_pv1_voltage
 pv1_current_110: sensor.sunsynk_pv1_current
 pv2_voltage_111: sensor.sunsynk_pv2_voltage
 pv2_current_112: sensor.sunsynk_pv2_current

**Comment by sabatex** [comment]
Which inverter model are you referring to? This program works with the Anenji 4-7.2 kW version.
